### PR TITLE
feat: ce 356 update and save hwc complaint assessment information

### PR DESCRIPTION
**Pull request by dmitri-korin-bcps**
# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Case Management changes for [CE-356](https://compenf.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-356).

- **Data Model Changes.** Migration scripts for creating and initializing database tables for the core case management objects. 
- **GraphQL queries.** Include objects like Case, Activity codes, Inaction reason code. 
- **GraphQL mutations.** Contain methods for creatin and modifying existing cases. The mutations return the object that was created/update to the caller.

_Both queries and mutations require authentication and membership in COS_OFFICER role_

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Verified that all the database tables for the data, history and a trigger function are created and reference data is loaded. Observed that flyway_schema_history table indicated the migrations were run successfully.
- [x] Successfully retrieved case objects and its dependencies in GraphQL Playground
- [x]	Successfully created new cases and updated the existing ones in GraphQL Playground.
- [x]	If invalid data is passed to a query or mutation the application does not crash but log an error message and respond with appropriate status

## GraphQL queries for testing
<details><summary>View GraphQL queries</summary>
<p>

### Create Assessment
```json
mutation CreateAssessment($createAssessmentInput: CreateAssessmentInput!) {
  createAssessment(createAssessmentInput: $createAssessmentInput) {
   caseIdentifier
   leadIdentifier
   assessmentDetails {
     actionNotRequired
     actionJustificationCode
     actionJustificationShortDescription
     actionJustificationLongDescription
     actionJustificationActiveIndicator
     actions {
       actor
       date
       actionCode
       shortDescription
       longDescription
       activeIndicator
      }
    }
  }
}
{
  "createAssessmentInput": {
    "leadIdentifier": "24-000021",
    "createUserId": "officerbob",
    "assessmentDetails": {
        "actionNotRequired": false,
        "actionJustificationCode": "OTHOPRPRTY",
        "actions": [{
          "actor": "61d6d74f-0442-4479-ae4d-ff814a4de15d",
          "date": "3/1/2019",
          "actionCode": "ASSESSHIST",
	  "activeIndicator": true
         }, 
         {
	   "actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
           "date": 1708578077,
	   "actionCode": "ASSESSRISK",
	   "activeIndicator": true
         },
         {
	   "actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
	   "date": 1708578078,
	   "actionCode": "CNFRMIDENT",
	   "activeIndicator": true
         },
         {
	   "actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
           "date": 1708578079,
	   "actionCode": "ASSESSHLTH",
           "activeIndicator": true
         }
       ]
    },
    "agencyCode": "COS",
    "caseCode": "HWCR"
  }
}
```

### Update Assessment
```json
mutation UpdateAssessment($updateAssessmentInput: UpdateAssessmentInput!) {
  updateAssessment(updateAssessmentInput: $updateAssessmentInput) {
   caseIdentifier
   leadIdentifier
   assessmentDetails {
     actionNotRequired
     actionJustificationCode
     actionJustificationShortDescription
     actionJustificationLongDescription
     actionJustificationActiveIndicator
     actions {
       actor
       date
       actionCode
       shortDescription
       longDescription
       activeIndicator
      }
    }
  }
}
{
"updateAssessmentInput": {
  "leadIdentifier": "24-000020",
  "caseIdentifier": "06cd489e-aa99-481f-b4dd-8506b0e4e64a",
   "updateUserId": "officerjohn",
   "assessmentDetails": {
      "actionNotRequired": true,
      "actionJustificationCode": "OTHOPRPRTY",
      "actions": [{
        "actor": "61d6d74f-0442-4479-ae4d-ff814a4de15d",
        "date": "3/1/2019",
	"actionCode": "ASSESSHIST",
         "activeIndicator": false
      }, 
      {
        "actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
	"date": 1708578077,
	"actionCode": "ASSESSRISK",
	"activeIndicator": true
      },
      {
      	"actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
	"date": 1708578078,
	"actionCode": "CNFRMIDENT",
	"activeIndicator": true
      },
      {
      	"actor": "a126bd2b-fc99-4fd0-a8cc-29ef4f595c97",
	"date": 1708578079,
	"actionCode": "ASSESSHLTH",
	"activeIndicator": true
      }]
    },
      "agencyCode": "COS",
      "caseCode": "HWCR"
  }
}
```

### Get Case and Assessment
```json
query { getCaseFile (caseIdentifier: "669f9bd7-e24f-4853-8158-9222a964d5f6")
 {
   caseIdentifier
   leadIdentifier
   assessmentDetails {
     actionNotRequired
     actionJustificationCode
     actionJustificationShortDescription
     actionJustificationLongDescription
     actionJustificationActiveIndicator
     actions {
       actor
       date
       actionCode
       shortDescription
       longDescription
       activeIndicator
      }
    }
  }
}
```
### Get Case and Assessment by Lead Id
```json
query { getCaseFileByLeadId (leadIdentifier: "24-000016")
 {
   caseIdentifier
   leadIdentifier
   assessmentDetails {
     actionNotRequired
     actionJustificationCode
     actionJustificationShortDescription
     actionJustificationLongDescription
     actionJustificationActiveIndicator
     actions {
       actor
       date
       actionCode
       shortDescription
       longDescription
       activeIndicator
      }
    }
  }
}
```

### Get Inaction Justification Types
```json
query { inactionJustificationTypes (agencyCode: "COS")
  {
    actionJustificationCode
    agencyCode
    shortDescription
    longDescription
    displayOrder
    activeIndicator
   }
}
```

### Get HWCR Assessment Actions
```json
query { HWCRAssessmentActions (actionTypeCode: "COMPASSESS")
{
  actionTypeCode
  actionCode
  displayOrder
  activeIndicator
  shortDescription
  longDescription
}
}
```
</p>
</details> 

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-compliance-enforcement-cm-32-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-compliance-enforcement-cm-32-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-compliance-enforcement-cm-32-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-compliance-enforcement-cm-32-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-compliance-enforcement-cm-32-backend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/merge.yml)

### CODE REVIEW

**Review by afwilcox — COMMENTED** [review]
@dmitri-korin-bcps 

Action Codes will need to have Short and Long descriptions returned in order for drop downs to function.

I'm not sure what the action_type_code on the CreateCaseFileInput mutation is for.   Is it required?

CreateCaseFile Mutations requires an input of AssessmentDetails, however there is no guarantee what order the sections are going to be entered in so this field should be optional if we are going to continue with this route, however  I actually don't think you want assessment_actions here at all in the mutation. The original design for both the queries and the mutation called for more specific queries and mutations.  This was based on the best practice to make mutations as specific as possible.   Right now the CreateCaseFile mutation is responsible for creating both the case and the Assessment, as we continue to add sections this is going to grow and it will eventually be quite unmaintainable.   I recommend that you remove the AssessmentDetails from CreatCaseFile Mutation and expose CreateAssessmentDetails as a top level mutation that will also create a case if it doesn't exist.

CreateAssessmentDetailsInput has assessment_actions as mandatory but I don't think this is correct because if action_not_requied_ind = 'N' there might not be any assessment actions provided (TBD on some requirements here maybe?)   

I was unable to call the CreateCaseFile Mutation - this is because it looks there is something odd in the prisma generation where both a case_guid and a case_file are required.  Only the case_guid was provided.

**Comment by dmitri-korin-bcps** [comment]
> @afwilcox 

> 
> Action Codes will need to have Short and Long descriptions returned in order for drop downs to function.
```diff
+ I modified the Action Codes query to return both short and long descriptions.
```
>
> I'm not sure what the action_type_code on the CreateCaseFileInput mutation is for. Is it required?
```diff
+ Action Type input parameter is to distinguish complaint assessment actions 
+ from other possible actions that we may introduce in future. It is not required. 
+ If not passed it default to “COMPASSESS”
```
> 
> CreateCaseFile Mutations requires an input of AssessmentDetails, however there is no guarantee what order the sections are going to be entered in so this field should be optional if we are going to continue with this route, however I actually don't think you want assessment_actions here at all in the mutation. The original design for both the queries and the mutation called for more specific queries and mutations. This was based on the best practice to make mutations as specific as possible. Right now the CreateCaseFile mutation is responsible for creating both the case and the Assessment, as we continue to add sections this is going to grow and it will eventually be quite unmaintainable. I recommend that you remove the AssessmentDetails from CreatCaseFile Mutation and expose CreateAssessmentDetails as a top level mutation that will also create a case if it doesn't exist.
```diff
+ The Case and AssessmentDetails objects are currently at the same level in the database. 
+ I can modify the app to merge Case and AssessmentDetails objects at the GraphQL level. 
+ We may leave mutation name CreateCase or change it to CreateAssessment. 
+ However, since there is no such object as Assessment at the data layer, 
+ I think it is more logical to name mutations CreateCase. 
+ The assessment details are just a subset of the case’s fields.  
+ Let me know what you think.
```
> 
> CreateAssessmentDetailsInput has assessment_actions as mandatory but I don't think this is correct because if action_not_requied_ind = 'N' there might not be any assessment actions provided (TBD on some requirements here maybe?)
```diff
+ CreateAssessmentDetailsInput has assessment_actions parameter which has an array type and is mandatory.  
+ If assessment does not require any actions, we pass an empty array in "assessment_actions" 
+ and the app will not associate any actions with the case then. 
+ I have just successfully tested it in GraphQL Playground.
```
> 
> I was unable to call the CreateCaseFile Mutation - this is because it looks there is something odd in the prisma generation where both a case_guid and a case_file are required. Only the case_guid was provided.
```diff
+ CreateCaseFile mutation does not require any id as an input parameter. It automatically generates a case id. 
+ See the screenshot. 
+ Please use the GraphQL queries that I included in the PR comment for testing.

![CreateCase](https://github.com/bcgov/nr-compliance-enforcement-cm/assets/108112696/0b96838b-a519-44e4-9531-ae83e0fde70d)

😄

**Comment by afwilcox** [comment]
@dmitri-korin-bcps  Thanks for the information regarding the changes to you made to the API design.    I do not believe we should be coupling our API design with our data model - one of the advantages of an API is to abstract the data model and provide business language functions to future front-end developers that are clearly described and self documenting.

Here are a couple of quotes from some reference articles that indicate why I had requested specialized queries and mutations over general ones.   (e.g. createAssessment as it's own endpoint instead of one massive case endpoint, and separate queries for each code table instead of a generic 'Actions' query)

- "Specificity. Make mutations as specific as possible. Mutations should represent semantic actions that might be taken by the user whenever possible." (https://www.apollographql.com/blog/designing-graphql-mutations)  
- "You may be tempted to create a mutation like sendEmail(type: PASSWORD_RESET) and call this mutation with all the different email types you may have. This is not a good design because it will be much more difficult to enforce the correct input in the GraphQL type system and understand what operations are available in GraphiQL." (same article as above)
- "Keep your mutations as small as possible" (https://towardsdatascience.com/graphql-best-practices-3fda586538c4)

I will surface this discussion on teams to get some broader input from the other developers and Ministry Architecture team.

**Comment by dmitri-korin-bcps** [comment]
@afwilcox 
These were valid bugs and now all are fixed in the most resent commit. 

The only point to note is in order to inactivate an action you have to specify it explicitly in the update query. 
For example, to deactivate ASSESSHIST while activating ASSESSRISK you need to put
```json
{ "updateCaseFileInput": {
            "case_file_guid": "7146da78-d64f-4112-8bf6-67c910ac4c10",
            "assessment_details": {
                "action_not_required_ind": true,
                "assessment_actions": 
                    [{
                        "actor_guid": "5c5283b3-6bdd-47ea-a647-e578249aa163",
                        "action_date": "3/1/2019",
                        "action_code": "ASSESSHLTH",
                        "active_ind": false
                    },
					{
                        "actor_guid": "5c5283b3-6bdd-47ea-a647-e578249aa163",
                        "action_date": "3/1/2019",
                        "action_code": "ASSESSRISK",
                        "active_ind": true
                    }
					]
            },
            "update_user_id": "POSTMAN"
        }
}
```

**Comment by marqueone-ps** [comment]
@afwilcox this is really throwing me off and is incredibly confusing, though I do agree with some of the refactored names, though if I may I'd also recommend changing the name of the base type from `case_file` to `assessment`.

I've been going back and forth between the docs and the apollo article you've posted and I'm not super sold on the idea of absolute specificity. If I were creating this first pass I would have created the following mutations 

```
type Mutation {
   upsertAssesment(input: AssesmentDto! | AssesmentWithEquipment | etc...): Assesment!
   deleteAssesment(id: Int)
}
```

What I feel like you're looking for is more along the lines of the following:
```
type Mutation { 
   createAssesment(input: AssementInput!): Assesment
   createAssesmentWithCase(input: AssementInput!): Assesment
   createAssesmentWithEquipment(input: AssementInput!): Assesment
   createAssesmentWithNotes(input: AssementInput!): Assesment
   createAssessmentAndMaybeCreateCaseIfItDoesntExist(input: AssesmentInput!): Assesment,
   updateAssesmentById(input: AssementInput!): int
   updateAssesmentByIdWithCase(input: AssementInput!): Int
   updateAssesmentByIdWithEquipment(input: AssementInput!): Int
   updateAssesmentByIdWithNotes(input: AssementInput!): Int
   deleteAssesment(id: int!)
}
```

When I look at this there's a lot going on, but more importantly our api surface area is now ten times bigger because of these extra very specific mutations, this is in turn going to increase the amount of mutation functions in the resolver. I also feel like we're going to end up with a log more code like this where we just chain methods together, unless each mutation is backed by its own host of helpers, for example: 
```
  @Mutation('createAssesmentWithEquipment')
  @Roles(Role.COS_OFFICER)
  createAssesmentWithEquipment(@Args('input') input: AssesmentInput) {
    return this.service.create(input).insertEquipment(input);
  }
```

Additionally this seems like something where we would end up falling into schema duplication because we have so many edge cases we're trying to handle: [Schema duplication](https://www.freecodecamp.org/news/five-common-problems-in-graphql-apps-and-how-to-fix-them-ac74d37a293c)

>Problem: Schema Duplication
One of the first things you realize when coding a GraphQL back-end from scratch is that it involves a lot of similar-but-not-quite-identical code, especially when it comes to schemas.

Now where I think specificity is absolutely paramount is in the example thats provided here: [apollo docs](https://www.apollographql.com/blog/designing-graphql-mutations) 

> For instance, say you were building a password reset feature into your app. To actually send that email you may have a mutation named: sendPasswordResetEmail. This mutation is more like an RPC call then a simple CRUD action on a data type.

This is the perfect example where specificity is going to be important instead of a simple:

```
type Mutation {
   sendEmail(email: String, type: String, body: String)
}
```
we would want to see 
```
type Mutation {
   sendPasswordResetEmail(input: EmailInput)
   sendForgotUsernameEmail(input: EmailInput)
...
}
```

Ultimately the graphql docs are very clear about one thing around names:  `<verb><noun>(input: <object type>)` and I think that Dmitri is doing that correctly.

One thing that is like nails on a chalk board for me is the fact we're including types in everything, its like we've taken a step backwards and we're back in the 80's again by using var names like `case_file_guid` or `note_text` when we start including the type in the var name, fine for database entities, but not something we want or need in the frontend.

**Comment by marqueone-ps** [comment]
@dmitri-korin-bcps for your input and return types I would highly recommend not using snake_case, and instead use camelCase. I think that for entities this is fine especially because the frontend is mostly expecting camelCase.

**Comment by afwilcox** [comment]
@marqueone-ps  - No, that's exactly what I'm trying to avoid.    I don't want to have an uber 'case' mutation that is called eleventy billion different ways.

I agree with @dmitri-korin-bcps that it makes sense to put the Case and the Assessment together in a single mutation (same with prevention and education and case; equipment and case; notes and case etc.   

While we might eventually want to create a createCase mutation on it's own - it's not technically required right now

**Comment by dmitri-korin-bcps** [comment]
@afwilcox

**Refactoring is complete.**
Like discussed in the call there are separate mutations for creating and updating assessments. Because of that there is no need for “case_file_guid” parameter in the createAssessment mutation. We already have updateAssessment mutation that accepts that.
Currently the workflow that covers both existing and new cases is as follows. 

1. Client run getCaseFile query
2. If the case exists getCaseFile returns case_file_guid
3. Client runs updateAssessment mutation and pass that case_file_guid to create actions and link them to the case.
4. If getCaseFile indicates that the case does not exist client runs createAssessment mutation which creates a new case and actions

If client does not know case_file_guid there is a query getCaseFileByLeadId to find the case associated with this lead Id.  Again if the case found client runs UpdateAssessment mutation and pass case_file_guid, otherwise createAssessment mutation.

_When testing remember that agencyCode and caseCode are now required parameters_. 
I am going to update the test queries and mutations in the PR comments shortly.

**Comment by afwilcox** [comment]
Thanks @dmitri-korin-bcps I'm going to try and do a bit more testing - but just by looking at the GQL definition it looks good.  I'm going to leave this PR open until we've got it fully integrated with the complaint management side in case the integration finds any issues.

One thing I thought of, and it relates to the comment by @marqueone-ps about using camelCase instead of snake_case it looks like you've just reused the database column names for the types.   My preference is that we would use more business friendly names in our API definition instead of our database columns which can get a bit gross sometimes.

I've updated the ticket specs to include what I was thinking we could use (as well as adding the short/long descriptions which you added, but I had missed in the original specification)

**Comment by dmitri-korin-bcps** [comment]
@afwilcox and @marqueone-ps 
I renamed the types to use camelCase like indicated in the ticket spec.

**Review by afwilcox — APPROVED** [review]

**Pull request merged**
